{
 "title": "JVM Performance & CPU Status [From: Prometheus]",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Application Uptime",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "process_uptime_seconds", "legendFormat": "Seconds" }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "Threads" }
   ]
  },
  {
   "title": "App Ready Time",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 4 },
   "targets": [
    { "expr": "application_ready_time_seconds", "legendFormat": "seconds" }
   ]
  },
  {
   "title": "CPU Usage Breakdown",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 8 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "JVM Process CPU" },
    { "expr": "system_cpu_usage", "legendFormat": "Total System CPU" }
   ]
  }
 ]
}