# Database connection settings (Change to matches your DB type/port)

spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=ju9999ba

# Automatically update your database schema to match your Java code structure

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true